### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by brignano** [brignano/restaurant-menu-creator#4]
Maybe there's someway we can present on Wednesday? If you look at his requirements we're really screwed. It's only 20% of our grade but I'd really like to pass the assignment, as I know you guys would as well.

﻿﻿Core requirements:
• JPA entity beans for the model with at least one mapping of either many-to-many or one-to-many
• Through application at least one place where you demonstrate understanding of each of these: create, update, delete, find (does not have to be same place)
• A complex flow element – a place where hitting “submit” on the page could take you one of several possible locations and the location must be determined by business logic (Class example was loan status determining whether to ask for more information about people, or home, or submit and save and show confirmation)
• Use of validation both built in and custom validation through your chosen framework (i.e. JSF or Spring)
• AJAX 
• Good MVC practices

**Comment by brignano** [comment]
Also I would do this right now but I seriously don't know what we have to show as far as his requirements go:

•       The project folder – full directory structure with config files, views, java, etc.
•       Word document – 2 sections
•       Instructions
•       Explain what I need to do to run your system and demonstrate each of the requirements above.  
•       Screen shots of various different parts of your application showing off that it is an application rather than just pages (this doesn’t need to be comprehensive, but should give a feel for the application).

**Comment by jmadsen45** [comment]
I agree. I wont have any time to work on it until tuesday and i do not think it is in a form that can be submitted currently.  Tuesday i can buckle down and try to get JPA entity beans working for our model so we can bind menus to users.  If we did this then we can have a complex business logic flow from the login:
When a user logs on it checks if they have any saved menus.  If they do then the controller sends them to the menu listing page that lists menus that they can edit(i can easily add an editing page if the Model entity bean is working, I already have one mocked up) .  If they do not have any menus saved then it sends them to the menu creation page.  

I think we will get a better grade if we submit it late.

**Comment by Kogurr** [comment]
Finally have the initial project hosted and working at: http://45.55.175.171:8080/menu/index.jsp
